### PR TITLE
Halwork

### LINKED ISSUE #56: Unhandled exception upon enabling interrupts
Upon `enable();` in kernel.c, we get an unhandled exception. Interrupt 32 is raised, which is the correct interrupt for IRQ 0, but the handler called is the one in idt.c, which is not the one that should be called. The issue is probably somewhere in wrappers.asm, irq.c, and/or isr.c.

### PR DESCRIPTION
**Pull request by BrandonKoerner**
TO ADD TO CHANGELOG:
- adds code to kernel.c main method for masking irq lines from PIC for IRQ0
- fixes #56 (issue was accidental call to isr_wrapper instead of irq_wrapper)
- changed TIMER_RATE to 1193 for now
- re-added commented-out code in libk/stdio/vprintf.c and defaulted to buffers of size 12 for internal itoa calls
- made isr_handler in kernel/kernel/hal/isr.c more verbose: now dumps all registers to terminal
- added a file (kernel-build-util.sh) for fast builds for testing
- prototyped irq_handler_install in kernel/hal.h

### CODE REVIEW

**Comment by BrandonKoerner** [comment]
TIMER_RATE at 1193 actually corresponds better to firing every millisecond

File: kernel-build-util.sh [hunk 1]
```diff
@@ -0,0 +1,12 @@
+#!/bin/bash
+
+# UTILITY SCRIPT FOR BUILDING KERNEL AND RUNNING IT WITH QEMU
```
Comment (davidaylaian) [inline kernel-build-util.sh:3]: I'll let this script in for now, but later I might try to add this functionality to the makefile

**Review by davidaylaian — APPROVED** [review]
